#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

cat <<EOF > $target/etc/network/interfaces
auto lo
iface lo inet loopback
auto $INTERFACE
iface $INTERFACE inet static
    address $IPADDR
    netmask $NETMASK
    gateway $GATEWAY
EOF

echo "nameserver $DNS" > $target/etc/resolv.conf

exit $error
