#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# remove crypt password from format.log
if [ -f $LOGDIR/format.log ]; then
    perl -i -pane "s/Executing: yes '.+?' \| cryptsetup/Executing: yes 'XXXXXXXXXXXXX' | cryptsetup/" $LOGDIR/format.log
fi

if [ "$FAI_ACTION" = "dirinstall" ] || ! inside_nfsroot ; then
  :
else
  # check if mdadm has been forgotten
  if grep -q active /proc/mdstat 2>/dev/null; then
    if [ ! -d $target/etc/mdadm ]; then
	echo ERROR: Found Software RAID, but the mdadm package was not installed
	error=1
    fi
  fi

  if [ -f $target/etc/crypttab ] && [ ! -f $target/sbin/cryptsetup ]; then
      echo ERROR: Encrypted devices used, but the crypsetup package was not installed.
      echo ERROR: You want to add cryptsetup-initramfs or dracut to some package_config file.
  fi

  usedm=$(dmsetup ls 2>/dev/null | egrep -v '^live-rw|^live-base|^No devices found' | wc -l)
  if [ $usedm -ne 0 ]; then
    if [ ! -d $target/etc/lvm ]; then
	echo ERROR: Found lvm devices, but the lvm2 package was not installed
	error=1
    fi
  fi
fi

[ "$FAI_DEBMIRROR" ] &&
  ainsl /etc/fstab "#$FAI_DEBMIRROR $MNTPOINT nfs ro 0 0"

# set bios clock
if [ $do_init_tasks -eq 1 ] ; then
    case "$UTC" in
       no|"") hwopt="--localtime" ;;
       yes)   hwopt="--utc"       ;;
    esac
    hwclock $hwopt --systohc || true
fi

# Make sure everything is configured properly
$ROOTCMD apt-get -f install -y

if [ $FAI_ACTION = "install" ]; then
    lskernels=$(echo $target/boot/vmlinu*)
    if [ ! -f ${lskernels%% *} ]; then
	echo "ERROR: No kernel was installed. Have a look at scripts.log" >&2
	error=1
    fi
fi

exit $error
