#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# a list of modules which are loaded at boot time
for module in $MODULESLIST; do
    ainsl -a /etc/modules "^$module$"
done

echo ${HOSTNAME%%.*} > $target/etc/hostname

ainsl -a /etc/mailname ${HOSTNAME}

# enable linuxlogo
if [ -f $target/etc/inittab ]; then
    fai-sed 's#/sbin/getty 38400#/sbin/getty -f /etc/issue.linuxlogo 38400#' /etc/inittab
elif [ -f $target/lib/systemd/system/getty@.service ]; then
    fai-sed 's#sbin/agetty --noclear#sbin/agetty -f /etc/issue.linuxlogo --noclear#' /lib/systemd/system/getty@.service
fi

# make sure a machine-id exists
if [ ! -f $target/etc/machine-id ]; then
    > $target/etc/machine-id
fi

# recreate machine-id if the file is empty
if [ X"$(stat -c '%s' $target/etc/machine-id 2>/dev/null)"  = X0 ] && [ -f $target/bin/systemd-machine-id-setup ]; then
    $ROOTCMD systemd-machine-id-setup
fi

fai-link /etc/mtab ../proc/self/mounts

rm -f $target/etc/dpkg/dpkg.cfg.d/unsafe-io

exit $error
