#!/bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

cat <<EOF > $target/etc/hosts
127.0.0.1 localhost
$IPADDR $HOSTNAME.$DOMAIN_ $HOSTNAME
EOF

rm -f $target/etc/hosts.orig

exit $error
