#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

username="ansible"

if [ -n "$username" ]; then
    if ! $ROOTCMD getent passwd $username ; then
        $ROOTCMD adduser --disabled-password --gecos "$username" $username
        $ROOTCMD usermod -p "$PASSWORD" $username
        $ROOTCMD usermod -aG sudo $username
        mkdir $target/home/$username/.ssh
        echo "$SSH_KEY" >> $target/home/$username/.ssh/authorized_keys
        $ROOTCMD chown -R "$username": /home/$username/.ssh
        $ROOTCMD chmod 0600 /home/$username/.ssh/authorized_keys
    fi
fi

exit $error
